[build]
  functions = ""  # The build command for your project
#   publish = "routes/index.js"         # The directory to publish after the build

# [[redirects]]                # Redirects configuration
#   from = "/*"
#   to = "/app.js"
#   status = 200
