[build]
  command = "npm run build"  # The build command for your project
  publish = "build/"         # The directory to publish after the build

[[redirects]]                # Redirects configuration
  from = "/*"
  to = "/index.html"
  status = 200